### PR TITLE
support the browser

### PR DESCRIPTION
**Pull request by ahdinosaur**
can i haz review @mmckegg :cat2:

### CODE REVIEW

**Comment by ahdinosaur** [comment]
random thoughts: i'm thinking this module should provide a readable stream of native audio, either using `node` or `browserify`, into a common ndarray format that we can build modules against. so far this only supports the microphone, but as `sox` supports input files and stdin streams, this module should also interface with the equivalent with web audio.

**Comment by mmckegg** [comment]
I see you are using [microphone-stream](https://github.com/saebekassebil/microphone-stream)

Internally that is just using Web Audio to get the mic stream and then connecting it to a [ScriptProcessorNode](https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode) to extract the buffers. 

I think you should just embed the code directly and bypass that module. It's only making things more complicated.

**Comment by mmckegg** [comment]
At https://github.com/saebekassebil/microphone-stream/blob/master/index.js#L35, `audioInput` could be any AudioNode.

**Comment by ahdinosaur** [comment]
sweet, thanks for the help.

**Comment by ahdinosaur** [comment]
merging, i'll do those updates as separate pushes.

**Comment by ahdinosaur** [comment]
[update based on your suggestions](https://github.com/livejs/read-audio/commit/9d34516a05011033f0eba7fb48ce34565e9f8712)

**Comment by mmckegg** [comment]
:+1:

**Pull request merged**
